### ISSUE TITLE
Website doesn't show Hidden unicode icons

### ISSUE THREAD

**Issue by FridiNaTor1** [LBPUnion/project-lighthouse#100]
When a user comments with a hidden unicode it appears as raw text on the website. Maybe implement a way of these unicodes to properly show up by taking the ones in the game, or recreating them so they look similar.

**Comment by jvyden** [comment]
What exactly do you mean by "hidden unicode"?

**Comment by FridiNaTor1** [comment]
For example &#xE001 is the X button. On the website you would see &#xE001 but in-game it will be an X button Icon

**Comment by FridiNaTor1** [comment]
Here's all of them I think. http://www.lbpcentral.com/forums/showthread.php?53863-LBP2-Hidden-Unicode-Icons-Hex-Code-List-and-Instructions-(Text-File)

**Comment by jvyden** [comment]
If you can find a GPL 3 compatible font with these, then yeah it shouldn't be too bad to implement. We don't have the resources to make one and I doubt one exists, so I'm closing this for now.
