### ISSUE TITLE
Implement account banning

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/project-lighthouse#103]
Add an option for server admins to prevent users and ips from accessing the server

**Comment by jvyden** [comment]
I can implement this for users but for ips thats for the admin to do through their firewall.

**Comment by ToruTheRedFox** [comment]
ipbans can be implemented too

Minecraft for example implements them

**Comment by jvyden** [comment]
I'll add IP banning if we can have it be more useful than having it done through a firewall. Otherwise, its just a point of failure we don't need.

**Comment by ToruTheRedFox** [comment]
ip banning by username would be a lot more convenient than digging out their ip manually

**Comment by jvyden** [comment]
> ip banning by username would be a lot more convenient than digging out their ip manually

Convenience does not solve security issues.

**Comment by jvyden** [comment]
Actually, I think I see your point. I'm still not going to add IP banning server-side, but it definitely would be useful to see some of the IP addresses a user has connected using.
