### ISSUE TITLE
Apostrophes don't display on website

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/project-lighthouse#108]
like holy shit please fix this
![Screenshot_20211217-145141_Chrome](https://user-images.githubusercontent.com/93880348/146554588-b03d6e06-4f03-4a84-98a1-979b5adc599e.png)

**Comment by LumaLivy** [comment]
Thanks for reporting the issue and providing a screenshot, my above pull request for the resolution will be merged soon when it's approved.

In the future, please try to keep the language in your bug reports civil and respectful. I don't want to be a drag but we're doing this in our free time, and if something this small is frustrating you or isn't being done fast enough you're welcome to make a pull request of your own -- that's the beauty of open source.
