### ISSUE TITLE
Regression: Cool levels broken on LBPV

### ISSUE THREAD

**Issue by jvyden** [LBPUnion/project-lighthouse#118]
Likely caused by #106

**Comment by turecross321** [comment]
note: other categories like most hearted, highest rated, and most played do not display any levels either on LBP Vita

**Comment by turecross321** [comment]
still doesn't seem to work on vita

**Comment by jvyden** [comment]
are you fully up to date?

**Comment by turecross321** [comment]
yes, it is up to date. 

just for clarification. from what i've gathered, the server gives the game an empty list while loading cool levels, and the same goes for some other categories too

could this be the issue?
![image](https://user-images.githubusercontent.com/51852312/150640620-27b02f76-c58e-4b62-9223-cf88a98ea9e8.png)
(no lbp vita in gameversion?)

**Comment by turecross321** [comment]
I captured the packet response thing and got this.

```
<slots
    hint_start="11">
    </slots>
```

**Comment by jvyden** [comment]
Yeah, that would probably do it.

**Comment by jvyden** [comment]
5450822 should fix this. Let me know if it does.

**Comment by turecross321** [comment]
yep, this seems to have fixed it! only problem left is that the server doesn't include the `total` parameter, so the next page button does not appear

**Comment by jvyden** [comment]
Gotcha. 31ad1cc should fix that.

**Comment by turecross321** [comment]
perfect👍

**Comment by jvyden** [comment]
Sick. Thanks for the help testing!
