### ISSUE TITLE
Reviewing levels

### ISSUE THREAD

**Issue by jvyden** [LBPUnion/project-lighthouse#27]

**Comment by Arcadius2006** [comment]
can we do this one next

**Comment by jvyden** [comment]
Mind taking this one? @LumaLivy

**Comment by LumaLivy** [comment]
Absolutely, I have a bit of work behind the scenes right now trying to make the review button appear. Sorry for the late response!

**Comment by jvyden** [comment]
No problem.

**Comment by LumaLivy** [comment]
Referencing #62 which adds nearly full support for reviews, but the "leave a review!" button does not appear in game. Needs more work.

**Comment by LumaLivy** [comment]
Closing this issue since level reviews are now implemented, however creating reviews is still scuffed (a workaround is needed to create a review in-game). Please see #107 for future updates on level reviews.
