### ISSUE TITLE
'Plays' on levels do not work on LBP Vita

### ISSUE THREAD

**Issue by hydronePVP45** [LBPUnion/project-lighthouse#42]
The total amount of people who have played a certain level does not work on LBP PSVita and is stuck on 0. 

I think it's got to do with the system that decides if a level was played on LBP1/LBP2/LBP3 as this worked on an older version of Lighthouse.
![image](https://user-images.githubusercontent.com/51852312/141675131-9e1c8dac-af8e-4aa6-89ca-60d8cd64ce04.png)

**Comment by Arcadius2006** [comment]
they don't work on LBP1 either

odd

**Comment by hydronePVP45** [comment]
fixed
