### ISSUE TITLE
Implement 'Remove All' button in queue.

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/project-lighthouse#43]
/LITTLEBIGPLANETPS3_XML/lolcatftw/clear
![image](https://user-images.githubusercontent.com/51852312/141675295-37e43095-e7ff-432d-af3a-1bf4e49990d4.png)

**Comment by jvyden** [comment]
Is this a GET or a POST? The method is also necessary.

**Comment by turecross321** [comment]
This is a post 

![image](https://user-images.githubusercontent.com/51852312/142075079-94d46654-8274-47a1-bf5b-743000eee136.png)
