### ISSUE TITLE
Next Page button not showing up on LBP Vita. 

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/project-lighthouse#44]
![image](https://user-images.githubusercontent.com/51852312/141679613-60ed80b7-3b10-4b7d-8182-fda14714a35b.png)
The game does not show a 'Next Page' button when there are more than 10 levels (every page contains 10 levels in LBP Vita). I do not have much more to say as I have no idea how this works

**Comment by jvyden** [comment]
Probably missing XML attributes. Shouldn't be too hard to solve.
