### ISSUE TITLE
Get size of level that is being downloaded in LBP Vita

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/project-lighthouse#45]
![image](https://user-images.githubusercontent.com/51852312/141680405-40cd7ee6-f0ea-460e-ba58-3b873a9da713.png)

**Comment by jvyden** [comment]
Is this pulled from an endpoint or is this calculated?

**Comment by turecross321** [comment]
I have since posting this found out that the game sends this while uploading the level.

`<slot type="user"> <name>Star Test example lmao xddddddd</name> <description>Shit</description> <icon>1c636160e366fb6c3aa7cc66eb05db3db17fe197</icon> <rootLevel>b2a8a4a3ebc8a5b8f3d6d79dbbb54387a6619712</rootLevel> <resource>0f51202219d623d7587866ae5ecdac655d1e823d</resource> <resource>2d1ea0ec56800bedc2d48c200b09686345d3c1a4</resource> <resource>39597804f24d64ec01a52c203a675ca93a2922a8</resource> <resource>3a1935843e82876b4998c3815bbddb1c2d83389a</resource> <resource>9daf4036787173b4326a6a827fe075c0daa887c4</resource> <resource>9e9aa2c5110918d3c79d86d82176a64f5bea4688</resource> <resource>9f1e280a5f639fb0330497fa1c53c1e9dec7d1e4</resource> <resource>b2a8a4a3ebc8a5b8f3d6d79dbbb54387a6619712</resource> <resource>c65d03de9e3453820d9b78c8a086e46048ec3cee</resource> <resource>f1f810786e378d1d371ab1e7708e79631446a838</resource> <location> <x>46549</x> <y>6778</y> </location> <initiallyLocked>false</initiallyLocked> <isSubLevel>false</isSubLevel> <isLBP1Only>false</isLBP1Only> <shareable>0</shareable> <background>107262</background> <links> </links> <internalLinks> </internalLinks> <leveltype></leveltype> <minPlayers>1</minPlayers> <maxPlayers>4</maxPlayers> <moveRequired>false</moveRequired> <sizeOfResources>698697</sizeOfResources> <acingEnabled>true</acingEnabled> <containsCollectabubbles>true</containsCollectabubbles> <enforceMinMaxPlayers>false</enforceMinMaxPlayers> <sameScreenGame>true</sameScreenGame> <customRewards> <customReward id="0"> <enabled>true</enabled> <description>Skidbapumbidbada 3 stars</description> <condition>score</condition> <amountNeeded>150.000000</amountNeeded> </customReward> <customReward id="1"> <enabled>true</enabled> <description>Holy duckong sichir oyiu got two stars</description> <condition>score</condition> <amountNeeded>100.000000</amountNeeded> </customReward> <customReward id="2"> <enabled>true</enabled> <description>You got one sar</description> <condition>score</condition> <amountNeeded>50.000000</amountNeeded> </customReward> </customRewards> </slot> `

`<sizeOfResources>698697</sizeOfResources>` is what I am guessing is the one we're looking for

**Comment by jvyden** [comment]
looks to be in bytes, shouldn't be too bad.

this will probably be calculated on-the-fly server-side

**Comment by turecross321** [comment]
Would that even be required? The game just sends that information while publishing

**Comment by jvyden** [comment]
It would cause desync issues if something changed server-side.

**Comment by turecross321** [comment]
Fair
