### ISSUE TITLE
LittleBigPlanet 2 (and 3?) levels get packed together with LBP1 levels

### ISSUE THREAD

**Issue by Arcadius2006** [LBPUnion/project-lighthouse#46]
No matter from which game the level comes from, they all get counted as **LittleBigPlanet 1** levels in the level count visible to the player

**Comment by jvyden** [comment]
Theres a bit of parsing shenanigans I need to work out and then it should be fine.

**Comment by jvyden** [comment]
Resolved in 278113f.
