### ISSUE TITLE
XML Injection

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/project-lighthouse#61]
it is currently possible to manipulate level info, by for example adding: `</description> <mmpick>true</mmpick>` in the description of a level which will make the game believe that the level is team picked

**Comment by jvyden** [comment]
Not an issue at this time, since it requires database modification.

**Comment by turecross321** [comment]
https://user-images.githubusercontent.com/51852312/142216609-f51d26e6-25bc-4586-875b-288dc64e7e96.mp4

**Comment by jvyden** [comment]
It just works, I guess.

**Comment by jvyden** [comment]
Try with that commit @turecross321

**Comment by turecross321** [comment]
Seems to have been fixed.
