### ISSUE TITLE
Put Network Settings in config file

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/project-lighthouse#85]

**Comment by alkalinethunder** [comment]
Can you please clarify what you mean by this? Do you mean settings for what port and IP addresses/hosts Lighthouse listens to?

**Comment by turecross321** [comment]
I am referring to the networksettings.nws file

**Comment by alkalinethunder** [comment]
Ah. Makes sense. And that's not too difficult to implement, I just don't see the benefit of it. Not sure how many of those settings actually do something useful in the game's client.

**Comment by turecross321** [comment]
Fair

**Comment by jvyden** [comment]
If you can give a list of useful options we can definitely implement some of them.

**Comment by jvyden** [comment]
I think we've put most of the useful options in for now. Please create a new issue if you need new ones.
